name: proyecto_movil_delivery_food_app_rodolfo_gonzalez
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0

  flutter_stripe: ^10.1.1

  http: ^1.2.1

  shared_preferences: ^2.2.3

  image_picker: ^1.1.2

  random_string: ^2.3.1

  firebase_storage: ^11.7.7

  firebase_core: ^2.24.2

  firebase_auth: ^4.16.0

  cloud_firestore: ^4.12.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository
  flutter_test:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.25.7
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/

